### ISSUE TITLE
Unpublish the resource if the resource is no more available

### ISSUE THREAD

**Issue by ondrejtomcik** [go-ocf/coap-gateway#17]
Let's assume device was online and published n resources. Device went offline, changed it's internal state - removed some resources, and went online again. In case it will not unpublish no more available resources, stored resources in the resource directory are invalid. This state is discovered immediately when the device is signed in because gateway observes each published and previously published resources. As it is no more available, device will return proper error code and gateway is supposed to mark the resource in the resource directory as unpublished one.

**Comment by jkralik** [comment]
Done by https://github.com/go-ocf/coap-gateway/pull/23
