### ISSUE TITLE
Implement storing and forwarding of access token in the Gateway

### ISSUE THREAD

**Issue by ondrejtomcik** [go-ocf/coap-gateway#8]
When the device connects to the OCF Cloud, it has to go through the sign-up and sign-in process. After successful sign-in, communication channel (TCP channel) is authorized. In case of OCF Devices, the access token is not send within each request, just when initiating the connection. The coap-gateway has to therefore store the access_token with user_id for each opened TCP connection and forward it further within each request to the OCF Cloud, as each operation must be authorized.

**Acceptance Criteria**

- access_token and user_id which are received and validated within the sign-in process are in case of successful sign-in persisted and attached to each following request coming from the device within the same TCP connection

**Comment by der-dano** [comment]
The issue resolved by adding an authorization context (device ID, user ID, access token) into each TCP connection.
